#ifndef TYPES
#define TYPES

enum JSONToken {
    TOKEN_CURLY_LEFT,
    TOKEN_CURLY_RIGHT,
    TOKEN_SQUARE_LEFT,
    TOKEN_SQUARE_RIGHT,
    TOKEN_DECIMAL,
    TOKEN_BOOLEAN,
    TOKEN_STRING,
    TOKEN_COLON,
    TOKEN_COMMA,
    TOKEN_REAL,
    TOKEN_NULL
};

enum JSONType {
    TYPE_OBJECT,
    TYPE_ARRAY,
    TYPE_STRING,
    TYPE_DECIMAL,
    TYPE_REAL,
    TYPE_BOOLEAN,
    TYPE_NULL
};

#endif // TYPES
